   version: '3'
   services:
     web:
       build: .
       ports:
         - "5000:5000"
       environment:
         - ELASTICSEARCH_HOST=elasticsearch
         - REDIS_HOST=redis
       depends_on:
         - elasticsearch
         - redis
     elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
       environment:
         - discovery.type=single-node
       ports:
         - "9200:9200"
         - "9300:9300"
     redis:
       image: redis:6
       ports:
         - "6379:6379"
